- .travis.yml
Signed-off-by: Michael Gielda <mgielda@antmicro.com>
> Use tuttest for CI

- .travis.yml
- README.md
- examples/eos-s3/Makefile
- examples/eos-s3/btn_counter.v
- examples/eos-s3/chandalar.pcf
- examples/eos-s3/quickfeather.pcf
This PR adds an EOS-S3 example
> Add QuickLogic EOS-S3 example

- README.md
- examples/xc7/counter_test/Makefile
- examples/xc7/environment.yml
> xc7: add 100t counter test

- README.md
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
> README: QL: update URL

- .travis.yml
- README.rst
- README.src.rst
- eos-s3/README.rst
- eos-s3/environment.yml
This pull requests tests the setup instructions on multiple different Linux OS (using Travis and Docker).
Supersede of #40
> Run tests on multiple Linux OS versions (using Travis). 

- README.rst
- xc7/README.rst
- xc7/counter_test/Makefile
Signed-off-by: Tim Callahan <tcal@google.com>
> Change arty_50 to arty_35 to match board branding.

- .github/workflows/tuttest.yml
> gh-actions: use actions/setup-python@v2

- xc7/requirements.txt
> pip: fix prjxray package name

- README.rst
This PR adds a readthedocs badge with the current status of sphinx documentation builds.
> README: Add readthedocs badge

- .github/workflows/sphinx-tuttest.yml
- README.rst
- docs/getting-symbiflow.rst
This PR adds tests on debian buster and debian bullseye to the CI
> Add debian buster and debian bullseye to CI tests

- docs/collect_readmes.py
This PR addresses the issues that came into light with #102, i.e. rendering inline blocks twice in Sphinx. It also enables adding more inline blocks in the future more easily.
> docs: handle strong and reference inline blocks

- xc7/requirements.txt
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
> xc7: point to exact prjxray commit

- xc7/linux_litex_demo/README.rst
Update excepts to expects in linux litex arty demo guide.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> Minor typo fix in arty linux litex demo guide

- .github/workflows/sphinx-tuttest.yml
> Add nightly cron job to symbiflow-examples.

- xc7/linux_litex_demo/README.rst
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
> xc7: litex: fix arty target

- docs/getting-symbiflow.rst
- xc7/environment.yml
- xc7/requirements.txt
> xc7: update packages

- docs/collect_readmes.py
- xc7/counter_test/Makefile
- xc7/counter_test/README.rst
- xc7/counter_test/nexys4ddr.xdc
Signed-off-by: Chandler Jearls <cjearls@vt.edu>
> added support for Nexys4DDR board in counter_test

- xc7/picosoc_demo/Makefile
- xc7/picosoc_demo/README.rst
- xc7/picosoc_demo/nexys4ddr.pcf
- xc7/picosoc_demo/nexys4ddr.v
Signed-off-by: Chandler Jearls <cjearls@vt.edu>
> adding support for the Nexys4DDR to PicoSoC example

- xc7/environment.yml
This PR allows using XDC constraints with `-dict`.
> Bump yosys plugins to leverage xc7 XDC dicts

- .github/scripts/build-examples.sh
> xc7: fix litex execution in CI

- .github/scripts/build-examples.sh
- docs/building-examples.rst
- docs/getting-symbiflow.rst
- eos-s3/environment.yml
- eos-s3/requirements.txt
> eos-s3: update environment, requirements and toolchain

- eos-s3/environment.yml
- xc7/environment.yml
> Fix conda python env config

- docs/getting-symbiflow.rst
- xc7/environment.yml
> xc7: update symbiflow packages

- docs/conf.py
- docs/requirements.txt
> Switch to sphinx_symbiflow_theme

- .github/scripts/generate_job_matrix.py
- .github/workflows/sphinx-tuttest.yml
Signed-off-by: Adam Olech <aolech@antmicro.com>
> ci: add non-preemptible exceptions

- .github/scripts/build-examples.sh
- .github/scripts/generate_job_matrix.py
- projf-makefiles/hello/hello-arty/B/Makefile
- projf-makefiles/hello/hello-arty/B/README.rst
- projf-makefiles/hello/hello-arty/C/Makefile
- projf-makefiles/hello/hello-arty/C/README.rst
- projf-makefiles/hello/hello-arty/D/Makefile
- projf-makefiles/hello/hello-arty/D/README.rst
- projf-makefiles/hello/hello-arty/E/Makefile
- projf-makefiles/hello/hello-arty/E/README.rst
- projf-makefiles/hello/hello-arty/F/Makefile
- projf-makefiles/hello/hello-arty/F/README.rst
- projf-makefiles/hello/hello-arty/G/Makefile
- projf-makefiles/hello/hello-arty/G/README.rst
- projf-makefiles/hello/hello-arty/H/Makefile
- projf-makefiles/hello/hello-arty/H/README.rst
- projf-makefiles/hello/hello-arty/I/Makefile
- projf-makefiles/hello/hello-arty/I/README.rst
- projf-makefiles/hello/hello-arty/J/Makefile
- projf-makefiles/hello/hello-arty/J/README.rst
- projf-makefiles/hello/hello-arty/K/Makefile
- projf-makefiles/hello/hello-arty/K/README.rst
- projf-makefiles/hello/hello-arty/L/Makefile
- projf-makefiles/hello/hello-arty/L/README.rst
This PR adds the other 11 designs from Project F's Hello Arty. This constitutes all of the designs from project F that currently work without modification (see issue #180). Each design has a short description in the readme file as well as the necessary commands to generate and download the bitstreams. The format and structure followed is the same as that of PR #181.
> Addition of all working project F designs

- docs/building-examples.rst
> docs: added note on env preparation

- .github/workflows/sphinx-tuttest.yml
- docs/getting-symbiflow.rst
- xc7/environment.yml
> xc7: bump packages

- xc7/linux_litex_demo/README.rst
> xc7: linux-litex: add information on the ethernet boot

- .github/scripts/build-examples.sh
- .github/scripts/common.sh
- .github/scripts/install-toolchain.sh
- .readthedocs.yml
- LICENSE
- Makefile
- docs/Makefile
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
> Relicense to Apache-2.0

- .github/scripts/generate_job_matrix.py
See https://github.com/SymbiFlow/symbiflow-examples/pull/198#discussion_r732841721.
> ci: add license header to generate_job_matrix.py

- docs/project-f.rst
> docs/project-f: fix ref to arch-defs issue

- .github/scripts/build-examples.sh
- docs/building-examples.rst
- docs/getting.rst
- xc7/requirements.txt
> install f4pga through pip and use envvars to support deprecated wrappers

- docs/building-examples.rst
- docs/getting.rst
- docs/personal-designs.rst
- xc7/additional_examples/button_controller/README.rst
- xc7/litex_demo/README.rst
Blocked by chipsalliance/f4pga#566.
> docs: s/INSTALL_DIR/F4PGA_INSTALL_DIR/

- docs/building-examples.rst
Cosmetic change to unfiy the naming convention with F4PGA_INSTALL_DIR
> Rename F4PGA_ENV_* to F4PGA_*_DIR

- .github/latest.patch
- .github/workflows/Latest.yml
- .github/workflows/sphinx-tuttest.yml
> Test latest packages from arch-defs

- .github/scripts/build-examples.sh
- .github/scripts/install-toolchain.sh
- docs/building-examples.rst
- docs/getting.rst
- eos-s3/environment.yml
- eos-s3/requirements.txt
- xc7/requirements.txt
This PR is cross-dependent with: 
* https://github.com/SymbiFlow/f4pga-arch-defs/pull/2821
* https://github.com/chipsalliance/f4pga/pull/587
> Fix inconsistency between QuickLogic and xc7 packages

- common/requirements.txt
- eos-s3/environment.yml
- eos-s3/requirements.txt
- xc7/environment.yml
- xc7/requirements.txt
Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>
> common: add requirements.txt and bump f4pga
