- linux_litex_demo/Makefile
- linux_litex_demo/arty.xdc
XDC constraints are necessary to have correct IOSTANDARDs
> linux_litex: add XDC constraints

- .travis.yml
- README.md
This PR simplifies the toolchain installation procedure. Also we switch to `vpr-no-gui` package, which has way less dependencies than regular `vpr`
> Simplify the toolchain installation

- .travis.yml
This PR adds QL build to the tuttest-based CI. This PR will fail in CI because the guide clones the https://github.com/SymbiFlow/symbiflow-examples repository and builds the examples. The examples are added int #17, so it has to be landed first.
Once #17 is megred this PR will have to be rebased, so it can run the tests from the repository.
> Add QuickLogic build to tuttest

- examples/xc7/environment.yml
This is required as the yosys package is updated with the new verison of yosys, which is currently incompatible with the synthesys scripts in the symbiflow installation tarball.
> xc7: fix yosys version

- README.md
- examples/xc7/counter_test/Makefile
- examples/xc7/environment.yml
- examples/xc7/linux_litex_demo/Makefile
- examples/xc7/picosoc_demo/Makefile
- examples/xc7/requirements.txt
This PR updates the xc7 install package with the latest progress. It currently uses the tarball produced by https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1504. Once that PR gets merged we can switch and use the tarball produced when running CI on master, and merge this PR.
For now, this PR is to test CI with the new packages.
Changes:
- use xc-fasm library to generate the bitstream
- added artix7 100T, zynq 020
> xc7: update install package and VTR version

- .travis.yml
- README.rst
- README.src.rst
- eos-s3/README.rst
- xc7/README.rst
- xc7/counter_test/Makefile
- xc7/environment.yml
- xc7/linux_litex_demo/Makefile
- xc7/linux_litex_demo/baselitex_arty.v
- Remove extra git clone of repo (which had mixed in code from master)
- Name all code blocks executed by tuttest
- Use "bash -ex -"
- Update conda packages and tarball to get IDELAYCTRL fix
- Remove LOC constraint on IDELAYCTRL in Linux example RTL
- Add 100T build for Linux example.
> Attempt to roll tarball and Yosys packages for symbiflow-examples.  Name the code blocks.   Address issue #48.

- .travis.yml
- README.rst
- eos-s3/README.rst
A small change to the naming in eos-s3/README.rst names means we can
simplify the .travis.yml to use the TOOLCHAIN value directly rather than
needing multiple if statements.
Also add comments to explain what is happening in each section.
Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>
> travis: Use toolchain name directly.

- .travis.yml
- README.rst
- xc7/README.rst
> Rework in-docker tests so they handle comments in scripts

- .travis.yml
In SymbiFlow scripts we use `realpath` - this tool is not present in CentOS 6 and Ubuntu Trusty. This PR disables tests in those systems.
Also, it temporally disables LiteX xc7 tests. Will reenable them once SymbiFlow support is fixed in upstream LiteX
> Drop CentOS 6 and Ubuntu Trusty

- eos-s3/environment.yml
`quicklogic-vtr` had to stay at the same version because newer versions
failed at building `btn_counter` example with the current quicklogic
toolchain used.
Other packages are in the versions built from their latest source
commits.
> eos-s3: Use Conda packages from LiteX-Hub channel

- xc7/environment.yml
These are the same versions of packages that have been successfully
tested in a PR for `symbiflow-arch-defs`: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1795
The `symbiflow-arch-defs` URL will be updated when the PR gets merged.
> xc7: Use Conda packages from LiteX-Hub channel

- README.rst
- xc7/README.rst
- xc7/counter_test/Makefile
- xc7/linux_litex_demo/Makefile
This PR separates the build directory for every board. 
This gives an opportunity to have bitstreams for various boards in the CI artifacts.
> xc7: Separate build directory for each board

- xc7/requirements.txt
This PR fixes the conda build during pip packages installation. Basically, the xc-fasm package was previously installing dependencies such as prjxray, which now should be installed in here, rather then allowing pip to install them automatically.
This is related to recent changes to the xc-fasm repo: SymbiFlow/xc-fasm#7
> xc7: fix python requirements

- README.rst
- xc7/README.rst
- xc7/environment.yml
Given that we still need to have a way to install only the required conda-packages with a minimal environment.yml file, this PR does not yet make use of the latest symbiflow packages links, but instead it adds the newest package, maintaining the links static, so that the conda packages of the various tools are in sync.
In addition, this adds also the z010 device package
> xc7: update to use latest packages

- .github/workflows/tuttest.yml
The eoan Ubuntu version (19.10) is causing failures on CI. Unsure whether there is  a temporary maintenance to the packages, but in general, it is worth to keep tested only the LTS OSes versions.
Example of failing build: https://github.com/SymbiFlow/symbiflow-examples/runs/1531376091?check_suite_focus=true
> ci: drop non-LTS eoan from CI tests

- README.rst
This PR fixes the link to the CI badge.
Closes https://github.com/SymbiFlow/symbiflow-examples/issues/96
> README: Fix link to GitHub Actions badge

- xc7/README.rst
The xc7 README should be removed, since now it is substituted by the sphinx-based documentation.
This change was missing in the initial PR with sphinx support: https://github.com/SymbiFlow/symbiflow-examples/pull/88
> Remove information covered in sphinx documentation from xc7 README 

- .github/workflows/sphinx-tuttest.yml
According to the @mithro's suggestion in https://github.com/SymbiFlow/symbiflow-examples/pull/99, this PR adds `debian testing (bullseye)` and `debian unstable (sid)` to the CI tests.
> Add debian bullseye and debian sid to CI tests

- xc7/linux_litex_demo/Makefile
The destination directory names for arty 35 and 100 were swapped in
refactoring.
Signed-off-by: Peter A. Bigot <pab@pabigot.com>
> xc7: fix linux_litex_demo build paths

- xc7/counter_test/Makefile
- xc7/linux_litex_demo/Makefile
- xc7/picosoc_demo/Makefile
Signed-off-by: Tim Callahan <tcal@google.com>
> Add .DELETE_ON_ERROR to Makefiles (issue #119).

- xc7/picosoc_demo/Makefile
The `BOARD_BUILDIR` was set but never used in `xc7/picosoc_demo/Makefile`. Solved (as used in the other examples).
> picosoc: fixed missing use of BOARD_BUILDIR

- eos-s3/environment.yml
- eos-s3/requirements.txt
This PR forces older (2020.2) version o the package. Never ones do not provide `libtbb.so.2` (required by VPR version we currently use)
> Force fixed tbb package version in eos-s3 env

- xc7/requirements.txt
This PR pins the xc-fasm version as new-packages need to be generated after https://github.com/SymbiFlow/xc-fasm/pull/11
> xc7: pin xc-fasm version

- common/Makefile
- xc7/counter_test/Makefile
- xc7/linux_litex_demo/Makefile
- xc7/picosoc_demo/Makefile
In response to the comments made by @acomodi and @kgugala  in [PR #167](https://github.com/SymbiFlow/symbiflow-examples/pull/167#discussion_r684103579), this PR moves the redundant pieces of the Makefiles throughout symbiflow-examples into a separate common Makefile that each design calls. For the common Makefile to work a user should specify the name of their target device (i.e. basys3, arty_35, zybo, etc.), the name of their top level module, their HDL design sources, any memory initialization files, and what constraint files they are using before calling the common Makefile. The common Makefile will take care of setting the various board parameters, as well as running the commands to build the design. I also added error checking for unsupported board types to the common makefile.   
I …
> Common Makefile

- eos-s3/requirements.txt
This PR pins the `quicklogic_fasm` version used by the toolchain to avoid incompatibilities throughout its development.
> Fix for eos-s3 FASM generation error

- docs/getting-symbiflow.rst
Clarifies that the conda_installer.sh script should be downloaded into
the git repository.
By habit, I place downloaded scripts into the ~/Downloads directory, and
avoid adding non-repo files to repositories. However, when I did that I
ended up with some difficult to diagnose bugs several steps later. It
was only on carefully rereading the instructions I realized what I ought
to have done. The intention of this change is to make clear to other new
users that they ought to place conda_installer.sh into the git repo
directory.
Signed-off-by: Alan Green <alan.green@gmail.com>
> getting-symbiflow.rst: Clarified download location

- .github/scripts/generate_job_matrix.py
- .github/workflows/sphinx-tuttest.yml
- docs/getting-symbiflow.rst
As per #30, this PR add 'Fedora latest' to the list of OS used in CI.
> Document the prerequisites on Fedora, and test in CI

- common/common.mk
This is so a change to any of these files (sources, xdc, sdc, pcf) will result in a recompile.   So, users can experiment with the provided examples or create their own and get normal Makefile behavior.
Signed-off-by: Brent Nelson <nelson@ee.byu.edu>
> Add SOURCES, XDC, SDC, and PCF to dependency in common.mk

- .github/scripts/generate_job_matrix.py
- .github/workflows/sphinx-tuttest.yml
Currently, the CI workflow expects self-hosted runners to exist. Therefore, it does not work on forks of this repo. This PR adds a condition in `generate_job_matrix.py` in order to change between `ubuntu-latest` and the self-hosted runners depending on the `github.repository` context value. Moreover, the set of tests to be executed on forks is reduced.
> ci: use default runners when running CI on a fork

- common/common.mk
Trailing whitespace in variable defs causes compile errrors.  This strips it out.
Signed-off-by: Brent Nelson <nelson@ee.byu.edu>
> Strip whitespace from variable definitions in common/common.mk

- .github/workflows/sphinx-tuttest.yml
This PR install `git` on the containers before using `actions/checkout`, instead of doing it afterwards.
On the one hand, we are already installing git later in each job, because the prerequisites in the docs include git. Therefore, this is just doing it before.
On the other hand, `actions/checkout` will fall back to the GitHub API if `git` is not found. Currently, this repo uses "Container jobs", which means that all the steps of the job are executed inside the container. Therefore, if `git` is not found, the Action uses the API, and that is undesirable because some features such as option `submodules` might not work. See:
> https://github.com/actions/checkout/#whats-new
> Fallback to REST API download
>
> * When Git 2.18 or higher is not in the PATH, the REST API will be used to …
> ci: install 'git' in the containers before cloning the repo

- .github/scripts/generate_job_matrix.py
A couple of months ago, Fedora 36 was failing, so we added Fedora 35 only (see #228). It seems that Fedora 36 is working now, so this PR adds it to the matrix.
> ci: test on Fedora 36

- .readthedocs.yml
See https://docs.readthedocs.io/en/stable/config-file/v2.html#python-version-legacy and SymbiFlow/symbiflow-arch-defs#2415.
> readthedocs: quote python version

- .github/scripts/generate_job_matrix.py
- .github/workflows/sphinx-tuttest.yml
CentOS 8 reached **EOL** in December 2021. As such it's no longer maintained and things start to break. Some package mirros fail to respond on-time or their transfer rate are too slow and are causing timeouts when installing packages, which causes the CI to occasionally fail on CentOS 8 images. [It also looks like packages are slowly being removed from the official CentOS 8 repos](https://www.centos.org/news-and-events/convert-to-stream-8/).
I believe it's time to deprecate support for this OS.
> Remove CentOS 8 from CI

- xc7/counter_test/counter_zynq.v
Trailing commas are not supported in port lists for module instances as per section 23.3.2 of the standard.
> Fix comma in counter module instance

- common/common.mk
I was following through the docs and noticed this was looking for files
in ~/opt/symbiflow
I could see changing this to use a variable, maybe, but I don't have any good
ideas for improving this to not assume the install is at ~/opt/f4pga.
> Modify board paths in common.mk to follow rename

- docs/building-examples.rst
- docs/getting.rst
- eos-s3/btn_counter/Makefile
- eos-s3/btn_counter/README.rst
- eos-s3/btn_counter/chandalar.pcf
- eos-s3/environment.yml
- eos-s3/requirements.txt
This PR is required in ongoing EOS-S3 upstreaming effort. It bumps yosys, yosys plugins, quicklogic-fasm and vtr packages. It also changes the part name in Makefile to uppercase and changes the ports in PCF file from single bit ones to multi bit because bumped VPR is now able to emit post-implementation netlist with merged multi bit ports.
> EOS-S3 update

- xc7/nightly.rst
This PR adds instructions on how to update systemverilog-plugin manually using the release from [plugin integration repository](https://github.com/antmicro/yosys-uhdm-plugin-integration/releases). It should then be available inside the f4pga flow.
> Add documentation on updating the plugin manually

- docs/requirements.txt
It seems that extension `sphinx_jinja` is not compatible with Sphinx v5 yet. See https://github.com/tardyp/sphinx-jinja/issues/35.
This PR pins sphinx to v4.5.0 in order to avoid broken builds on RTD: https://readthedocs.org/projects/f4pga-examples/builds/.
> docs/requirements: temporarily pin sphinx to v4.5.0

- docs/getting.rst
- xc7/environment.yml
- xc7/requirements.txt
This PR updates locked dependencies in the xc7 conda environment to the latest versions (as of July 18th).
> xc7: dependency updates

- eos-s3/btn_counter/Makefile
- eos-s3/btn_counter/flow.json
Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>
> eos-s3: btn_counter: use F4PGA build flow by default

- docs/getting.rst
~Blocked by https://github.com/chipsalliance/f4pga/pull/588.~
> docs/getting: guidelines to bump the yosys plugin moved to conda-eda

- docs/building-examples.rst
- docs/xc7/linux_litex_demo.rst
- docs/xc7/litex_sata_demo.rst
- xc7/litex_sata_demo/README.rst
> docs/building-examples: add linux_litex_demo and litex_sata_demo
